name: templates
description: Reusable ThemeExtension templates for building Flutter design systems.
publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  theme_extensions_gen_annotations: any

dev_dependencies:
  build_runner: ^2.4.15

  theme_extensions_gen: ^0.1.4
