include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_single_quotes: true
    avoid_dynamic_calls: true
    public_member_api_docs: false
    sort_pub_dependencies: false
    use_setters_to_change_properties: false
    one_member_abstracts: false

analyzer:

  errors:
    undefined_prefixed_name: ignore
    invalid_annotation_target: ignore

  exclude: [ build/**, lib/**.g.dart ]